#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-one-shot-updates
Version  : 3
Release  : 3
URL      : http://localhost/cgit/projects/clr-one-shot-updates/snapshot/clr-one-shot-updates-3.tar.bz2
Source0  : http://localhost/cgit/projects/clr-one-shot-updates/snapshot/clr-one-shot-updates-3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: clr-one-shot-updates-license = %{version}-%{release}

%description
No detailed description available

%package license
Summary: license components for the clr-one-shot-updates package.
Group: Default

%description license
license components for the clr-one-shot-updates package.


%prep
%setup -q -n clr-one-shot-updates-3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555634867
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1555634867
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-one-shot-updates
cp COPYING %{buildroot}/usr/share/package-licenses/clr-one-shot-updates/COPYING
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/swupd/one-shot-updates/201904-reconfigure-network-manager.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-one-shot-updates/COPYING
