#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-one-shot-updates
Version  : 6
Release  : 6
URL      : http://localhost/cgit/projects/clr-one-shot-updates/snapshot/clr-one-shot-updates-6.tar.bz2
Source0  : http://localhost/cgit/projects/clr-one-shot-updates/snapshot/clr-one-shot-updates-6.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: clr-one-shot-updates-license = %{version}-%{release}

%description
No detailed description available

%package license
Summary: license components for the clr-one-shot-updates package.
Group: Default

%description license
license components for the clr-one-shot-updates package.


%prep
%setup -q -n clr-one-shot-updates-6
cd %{_builddir}/clr-one-shot-updates-6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589415284
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1589415284
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/clr-one-shot-updates
cp %{_builddir}/clr-one-shot-updates-6/COPYING %{buildroot}/usr/share/package-licenses/clr-one-shot-updates/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/clr-one-shot-updates/4cc77b90af91e615a64ae04893fdffa7939db84c
